import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import Banner from '../components/Banner';

const Home: NextPage = () => {
  const handleOnBannerBtnClick = () => {
    console.log('hi banner button!');
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Commoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner buttonText="View stores nearby" handleOnClick={handleOnBannerBtnClick} />
      </main>
    </div>
  )
}

export default Home
